version: '3.8'

services:
  # API Backend
  api:
    build:
      context: .
      target: api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/products.db
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - CROSS_ENCODER_MODEL=cross-encoder/ms-marco-MiniLM-L-6-v2
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      - data-setup
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Streamlit UI
  ui:
    build:
      context: .
      target: ui
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped

  # Data ingestion service (runs once)
  data-setup:
    build:
      context: .
      target: data-processor
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/products.db
    command: >
      sh -c "
        python src/etl/ingest_data.py &&
        python src/indexing/build_index.py &&
        python src/models/ctr_model.py
      "

  # Optional: Jupyter notebook for development
  notebook:
    build:
      context: .
      target: base
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: >
      sh -c "
        pip install jupyterlab &&
        jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
      "
    profiles:
      - dev

volumes:
  data_volume:
    driver: local